[package]
name = "drv-gimlet-seq-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
ringbuf = {path = "../../lib/ringbuf"}
zerocopy = "0.3.0"
byteorder = {version = "1.4", default-features = false}
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-spi = {path = "../stm32h7-spi", default-features = false }
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api", default-features = false}
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api"}
drv-spi-api = {path = "../spi-api"}
drv-ice40-spi-program = {path = "../ice40-spi-program"}
drv-i2c-api = {path = "../i2c-api"}
drv-i2c-devices = {path = "../i2c-devices"}
cortex-m = { version = "0.7", features = ["inline-asm"] }
cfg-if = "0.1.10"
gnarle = {path = "../../lib/gnarle"}

[build-dependencies]
build-util = {path = "../../build/util"}
build-i2c = {path = "../../build/i2c"}
gnarle = {path = "../../lib/gnarle"}
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0"


[features]
default = ["standalone"]
standalone = ["h753"]
h753 = ["drv-stm32h7-spi/h753", "drv-stm32h7-rcc-api/h753"]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"
