name = "gimlet"
base-toml = [
    "stm32h743.toml",
    "board.toml",
]
stacksize = 1024

[kernel]
path = "."
name = "gimlet"
requires = {flash = 32768, ram = 4096}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

[supervisor]
notification = 1

# Flash sections are mapped into flash bank 1 (of 2).
[outputs]
flash = {memory = "flash_bank_0"}
ram = {memory = "dtcm"}

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 16384, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.rcc_driver]
path = "../../drv/stm32h7-rcc"
name = "drv-stm32h7-rcc"
features = ["h753"]
priority = 1
requires = {flash = 8192, ram = 1024}
uses = ["rcc"]
start = true

[tasks.gpio_driver]
path = "../../drv/stm32h7-gpio"
name = "drv-stm32h7-gpio"
features = ["h753"]
priority = 2
requires = {flash = 8192, ram = 1024}
uses = ["gpios1", "gpios2", "gpios3"]
start = true
task-slots = ["rcc_driver"]

[tasks.spi4_driver]
path = "../../drv/stm32h7-spi-server"
name = "drv-stm32h7-spi-server"
priority = 2
requires = {flash = 16384, ram = 4096}
features = ["spi4", "h753"]
uses = ["spi4"]
start = true
interrupts = {"spi4.irq" = 0}
stacksize = 1000
task-slots = ["gpio_driver", "rcc_driver"]

[tasks.spi4_driver.config.spi]
global_config = "spi4"

[tasks.spi2_driver]
path = "../../drv/stm32h7-spi-server"
name = "drv-stm32h7-spi-server"
priority = 2
requires = {flash = 16384, ram = 4096}
features = ["spi2", "h753"]
uses = ["spi2"]
start = true
interrupts = {"spi2.irq" = 0}
stacksize = 1000
task-slots = ["gpio_driver", "rcc_driver"]

[tasks.spi2_driver.config.spi]
global_config = "spi2"


[tasks.i2c_driver]
path = "../../drv/stm32h7-i2c-server"
name = "drv-stm32h7-i2c-server"
features = ["h753", "itm"]
priority = 2
requires = {flash = 16384, ram = 2048}
uses = ["i2c2", "i2c3", "i2c4"]
start = true
task-slots = ["gpio_driver", "rcc_driver"]

[tasks.i2c_driver.interrupts]
"i2c2.event" = 1
"i2c2.error" = 2
"i2c3.event" = 2
"i2c3.error" = 2
"i2c4.event" = 3
"i2c4.error" = 3

[tasks.spd]
path = "../../task/spd"
name = "task-spd"
features = ["h753", "itm"]
priority = 2
requires = {flash = 16384, ram = 16384}
uses = ["i2c1"]
start = true
task-slots = ["gpio_driver", "i2c_driver", "rcc_driver"]

[tasks.spd.interrupts]
"i2c1.event" = 0
"i2c1.event" = 0

[tasks.thermal]
path = "../../task/thermal"
name = "task-thermal"
features = ["itm", "h753"]
priority = 3
requires = {flash = 65536, ram = 8192 }
stacksize = 2048
start = true
task-slots = ["i2c_driver"]

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
features = ["h753", "stm32h7", "itm", "i2c", "gpio", "spi", "qspi"]
priority = 3
requires = {flash = 32768, ram = 32768 }
start = true
task-slots = ["gpio_driver", "hf", "i2c_driver"]

[tasks.gimlet_seq]
path = "../../drv/gimlet-seq-server"
name = "drv-gimlet-seq-server"
features = ["h753"]
priority = 3
requires = {flash = 32768, ram = 1024 }
stacksize = 1024
start = true
task-slots = ["gpio_driver", {spi_driver = "spi2_driver"}]

[tasks.hf]
path = "../../drv/gimlet-hf-server"
name = "drv-gimlet-hf-server"
features = ["h753"]
priority = 3
requires = {flash = 16384, ram = 2048 }
stacksize = 2048
start = true
uses = ["quadspi"]
interrupts = {"quadspi.irq" = 0}
task-slots = ["gpio_driver", "rcc_driver"]

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 256, ram = 256}
stacksize = 256
start = true
