target = "thumbv7em-none-eabihf"
stacksize = 1024

[memory.flash_bank_0]
address = 0x08000000
size = 1048576
read = true
execute = true

[memory.flash_bank_1]
address = 0x08100000
size = 1048576
read = true
execute = true

[memory.dtcm]
address = 0x20000000
size = 131072
read = true
write = true
# DTCM can technically be executed, but we don't expect it to be.
execute = false 

[peripherals.rcc]
address = 0x58024400
size = 1024

[peripherals.gpios1]
address = 0x58020000
size = 0x2000

[peripherals.gpios2]
address = 0x58022000
size = 0x0800

[peripherals.gpios3]
address = 0x58022800
size = 0x0400

[peripherals.spi2]
address = 0x40003800
size = 1024
interrupts = { irq = 36 }

[peripherals.spi4]
address = 0x40013400
size = 1024
interrupts = { irq = 84 }

[peripherals.usart3]
address = 0x40004800
size = 1024

[peripherals.i2c1]
address = 0x40005400
size = 1024
interrupts = { event = 31, error = 32 }

[peripherals.i2c2]
address = 0x40005800
size = 1024
interrupts = { event = 33, error = 34 }

[peripherals.i2c3]
address = 0x40005c00
size = 1024
interrupts = { event = 72, error = 73 }

[peripherals.i2c4]
address = 0x58001c00
size = 1024
interrupts = { event = 95, error = 96 }

[peripherals.quadspi]
address = 0x52005000
size = 4096
interrupts = { irq = 92 }
