name = "demo-sfe"
target = "thumbv7em-none-eabihf"
board = "sfe"
stacksize = 1024

[kernel]
path = "."
name = "demo-sfe"
requires = {flash = 65536, ram = 4096}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm", "ambiq-apollo3-pac"]

[supervisor]
notification = 1

[outputs.flash]
address = 0x0000C000
size = 999424
read = true
execute = true

[outputs.ram]
address = 0x10000000
size = 393216
read = true
write = true
execute = true

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 32768, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.pwrctrl_driver]
path = "../../drv/apollo3-pwrctrl"
name = "drv-apollo3-pwrctrl"
features = ["ambiq-apollo3-pac"]
priority = 1
requires = {flash = 8192, ram = 1024}
uses = ["pwrctrl"]
start = true


[tasks.usart_driver]
path = "../../drv/apollo3-usart"
name = "drv-apollo3-usart"
features = ["ambiq-apollo3-pac"]
priority = 2
requires = {flash = 16384, ram = 1024}
# uses = ["usart2", "gpioa"]
uses = ["uart0", "gpio"]
start = true
interrupts = {15 = 1}
task-slots = ["pwrctrl_driver"]

[tasks.itm_driver]
path = "../../drv/apollo3-itm"
name = "drv-apollo3-itm"
features = ["ambiq-apollo3-pac"]
priority = 2
requires = {flash = 16384, ram = 1024}
# uses = ["uart0", "gpio"]
start = true
# interrupts = {15 = 1}
# task-slots = ["pwrctrl_driver"]

[tasks.user_leds]
path = "../../drv/user-leds"
name = "drv-user-leds"
features = ["ambiq-apollo3-pac"]
priority = 2
requires = {flash = 16384, ram = 1024}
uses = ["gpio"]
start = true

[tasks.ping]
path = "../../task/ping"
name = "task-ping"
features = ["uart"]
priority = 4
requires = {flash = 8192, ram = 512}
stacksize = 512
start = true
task-slots = [{peer = "pong"}, "usart_driver"]

[tasks.pong]
path = "../../task/pong"
name = "task-pong"
priority = 3
requires = {flash = 8192, ram = 1024}
start = true
task-slots = ["user_leds"]

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
priority = 3
requires = {flash = 32768, ram = 16384 }
stacksize = 2048
start = true

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 256, ram = 256}
stacksize = 256
start = true

# [peripherals.usart2]
# address = 0x40004400
# size = 1024
[peripherals.uart0]
address = 0x4001C000
size = 0x400

# [peripherals.rcc]
# address = 0x40023800
# size = 1024

# [peripherals.gpioa]
# address = 0x40020000
# size = 1024

# [peripherals.gpiod]
# address = 0x40020c00
# size = 1024
[peripherals.gpio]
address = 0x40010000
size = 0x400

[peripherals.pwrctrl]
address = 0x40021000
size = 0x40
